### PR TITLE
feat(APIv2): RHINENG-10053 value editing on tailorings

### PR DESCRIPTION
**Pull request by skateman**
Forgot this one 🤷 

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by LightOfHeaven1994** [comment]
I quickly tested in ephemeral and it works! Great job David! :heart: 

```
In [28]: r = safe_patch_request(app, f"/policies/{policy_data['id']}/tailorings/{tailoring['id']}", {"value_overrides": {"f5da6181-553b-45e0-a6b7-5dc318b17ffa": "44", "16b
    ...: 82c07-86f5-4323-8e66-ad0eafa5c9c4": "0"}})

In [29]: r
Out[29]: <Response [202]>

In [30]: r.json()
Out[30]: 
{'data': {'id': '839e1d47-3500-4ad9-a36d-2a77eb69d8df',
  'profile_id': '0db0d4bd-9608-44e8-8a12-a7694d4ec383',
  'os_minor_version': '4',
  'value_overrides': {'f5da6181-553b-45e0-a6b7-5dc318b17ffa': '44',
   '16b82c07-86f5-4323-8e66-ad0eafa5c9c4': '0'},
  'type': 'tailoring',
  'os_major_version': 9}}
```
Checked number validation, also looks good 
```
In [31]: r = safe_patch_request(app, f"/policies/{policy_data['id']}/tailorings/{tailoring['id']}", {"value_overrides": {"f5da6181-553b-45e0-a6b7-5dc318b17ffa": "44", "16b
    ...: 82c07-86f5-4323-8e66-ad0eafa5c9c4": "value should be number"}})

...

HTTPError: 406 Client Error: Not Acceptable for url: http://compliance-service.ephemeral-9gjtz5.svc:8000/api/compliance/v2/policies/296fb446-0763-479f-a33d-bddb17d680b4/tailorings/839e1d47-3500-4ad9-a36d-2a77eb69d8df
```

**Review by LightOfHeaven1994 — APPROVED** [review]

**Comment by skateman** [comment]
@LightOfHeaven1994 we don't test the lower/upper bound of numbers, mainly because these fields are not utilized by any of our content.

**Comment by LightOfHeaven1994** [comment]
@skateman that's completely fine. 406 error I pasted is expected as I tried to update value that has to be a number but I provided foo string. We are good to merge this one

**Review by romanblanco — APPROVED** [review]
LGTM :+1:

**Pull request merged**
