### PR TITLE
[stable] Align stable to master

### PR DESCRIPTION
**Pull request by akofink**
RHICOMPL-1374
RHICOMPL-1080
RHICOMPL-1371

:no_smoking:

### CODE REVIEW

**Comment by Victoremepunto** [comment]
@akofink  I think we still need the "update compliance_user privileges on the PR" . Our Smoke tests are failing because the Compliance user does not have permissions to read any table in the DB .

**Comment by akofink** [comment]
Added RHICOMPL-1371

**Comment by akofink** [comment]
Here's an attempt at fixing RHICOMPL-1379: https://github.com/RedHatInsights/compliance-backend/pull/726

**Review by vkrizan — APPROVED** [review]
Thanks!

**Comment by vkrizan** [comment]
Closing in favor of #728

**Pull request closed without merging**
