### PR TITLE
[stable] Align stable to master

### PR DESCRIPTION
**Pull request by akofink**
RHICOMPL-1334
RHICOMPL-1265
RHICOMPL-1397
RHICOMPL-1285
RHICOMPL-1414
RHICOMPL-1223
RHICOMPL-826
RHICOMPL-1415
RHICOMPL-1413

:no_smoking:

### CODE REVIEW

**Review by vkrizan — APPROVED** [review]
Thanks.

**Comment by akofink** [comment]
We're having an issue with an old migration which migrates data (not a schema migration). It's removed in https://github.com/RedHatInsights/compliance-backend/pull/736.

**Comment by akofink** [comment]
Well, it looks pretty good. We have the 1 failing rbac test that we expected, plus this failure:

```
assert False
 +  where False = <Response [500]>.ok
Stacktrace
application = <iqe.base.application.Application object at 0x7fbb6ba38780>
report_with_internal_policy_module = (System(name='RHIQE.SniVBJ.test', _id='99703962-3669-461a-9247-802323a03b7b', _os_major_version=7, _os_minor_version=8...unt=0, tailored=False, canonical=True, ssg_version='0.1.52', parent_profile=None, parent_name=None), parent_name=None))
    @pytest.mark.outage
    def test_graphql_search_by_name(application, report_with_internal_policy_module):
        """Check if profiles can be retrieved via graphql after filling "search by name"
    
        Polarion:
            assignee: eshamard
            linkedWorkItems: compliance_graphql
        """
        system, _ = report_with_internal_policy_module
        systems_filter = f"has_test_results = true and {system.name}"
        resp = application.compliance.graphql_client.get_reported_systems(filter=systems_filter)
>       assert resp.ok
E       assert False
E        +  where False = <Response [500]>.ok
/iqe_venv/lib64/python3.6/site-packages/iqe_compliance/tests/test_graphql.py:133: AssertionError
```

**Comment by akofink** [comment]
Alright! I think we're good here. There's one failure, which is expected due to the cert-auth changes that went in recently.

```
FAILED tests/test_rbac.py::test_rbac_cert_type_auth - assert False

= 1 failed, 90 passed, 156 deselected, 1 xfailed, 3 warnings in 466.58s (0:07:46)
```

**Pull request merged**
