### PR TITLE
feat(rails): RHICOMPL-1318 enable parallel testing

### PR DESCRIPTION
**Pull request by skateman**
It should fork processes based on the number of cores on your machine.

### CODE REVIEW

**Review by marleystipich2 — APPROVED** [review]
This all looks good to me! Thanks, @skateman

**Comment by skateman** [comment]
@marleystipich2 have you tried to run the tests locally?

**Review by marleystipich2 — COMMENTED** [review]
@skateman I ran these tests locally with docker-compose and there were some errors and failures in `test/services/ssg_config_downloader`. I'm not sure how much detail you need about which tests failed/errored but here's a screenshot of the logs.

Screen Shot 2021-12-21 at 5 39 17 PM

**Comment by marleystipich2** [comment]
The tests passed this time! Everything looks great. Thanks, @skateman!

**Pull request merged**
