### PR TITLE
docs(OpenAPI): RHICOMPL-3255 remove obsolete 'name' attribute

### PR DESCRIPTION
**Pull request by romanblanco**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by LightOfHeaven1994** [comment]
@romanblanco can we remove id here too?

**Comment by skateman** [comment]
Will this not be overridden by the rake task? Ideally you should fix the problem in the serializer if these fields are obsolete.

**Comment by romanblanco** [comment]
@skateman Updated the PR to include the changes of rake task. The values are correctly removed from `openapi.json` file.

**Review by skateman — APPROVED** [review]
The Seal of Approval

**Pull request merged**
