### PR TITLE
[stable] Align stable to master

### PR DESCRIPTION
**Pull request by akofink**
RHICOMPL-1312
RHICOMPL-1301
RHICOMPL-1151

:no_smoking:

### CODE REVIEW

**Review by sthirugn — APPROVED** [review]

**Comment by akofink** [comment]
@Victoremepunto seeing some issues with rbac here. I'm re-running the job. :crossed_fingers:

**Comment by akofink** [comment]
It may be related to the SSO outage which is still ongoing as of 8pm ET :disappointed: Please re-run smoke tests tomorrow.

**Review by vkrizan — APPROVED** [review]
Thanks!

**Comment by akofink** [comment]
Merging as is with failing smoke tests due to rbac issues. We will continue to verify in QA.

**Pull request merged**
