### PR TITLE
Add stage for running floorist tests

### PR DESCRIPTION
**Pull request by prichard77**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by prichard77** [comment]
Can someone help me get the correct format to pass linting and also help review and eventually merge this PR. I have tried to update my commit formats but I keep getting errors. Also, when I see what older merge requests are named, I wonder if I need to update my name also?

**Comment by RoamingNoMaD** [comment]
> Can someone help me get the correct format to pass linting and also help review and eventually merge this PR. I have tried to update my commit formats but I keep getting errors. Also, when I see what older merge requests are named, I wonder if I need to update my name also?

The [lint](https://github.com/RedHatInsights/compliance-backend/blob/master/.commitlint.yml) forces a format similar to conventional commits, so all commits should have format:

`<type>(<OPTIONAL scope>): <OPTIONAL ticket> <subject>`

e.g.:

`feat(APIv2): RHINENG-12245 enable APIv2 for everyone`

**Comment by vkrizan** [comment]
@prichard77 Would you be able to clean up the commits?

Screenshot 2024-12-11 at 10-48-32 Add stage for running floorist tests by prichard77 · Pull Request #2315 · RedHatInsights_compliance-backend

PRs should not include commits that are fixing things introduced in the same PR or are temporary (e.g. to test those fixes). Please use (interactive) rebase to amend the commits.

Thank you.

**Comment by prichard77** [comment]
yes, I intend to squash these commits. I am stumbling a bit with this setup/env. I hope to get this cleaned up.

**Comment by prichard77** [comment]
Finally got past the linter. I was confused and thinking my new, formatted commits were all failing lint, but it was complaining about the older commits where I had the format wrong.

**Review by RoamingNoMaD — APPROVED** [review]
lgtm

**Pull request merged**
