### PR TITLE
cleanup(clowder): RHICOMPL-3779 drop the legacy clowder template

### PR DESCRIPTION
**Pull request by skateman**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by romanblanco — APPROVED** [review]
LGTM :+1:

**Comment by skateman** [comment]
@Victoremepunto right, forgot about the README, app-interface is consuming from the right location already.

**Comment by skateman** [comment]
@LightOfHeaven1994 there seems to be a weird CI issue here :disappointed:

**Pull request merged**
