### PR TITLE
chore(devel): upgrade PostgreSQL to v15 in dev and ephemeral

### PR DESCRIPTION
**Pull request by skateman**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by vkrizan — APPROVED** [review]
Make sense

**Comment by skateman** [comment]
@Victoremepunto then how the CI is passing? :thinking:

**Comment by vkrizan** [comment]
@Victoremepunto it is https://github.com/RedHatInsights/clowder/blob/99ccd6331a30f0ee0a77258bfa28d4ae4ac4d79e/controllers/cloud.redhat.com/providers/database/provider.go#LL43C16-L43C16

**Comment by Victoremepunto** [comment]
> 

> @Victoremepunto it is https://github.com/RedHatInsights/clowder/blob/99ccd6331a30f0ee0a77258bfa28d4ae4ac4d79e/controllers/cloud.redhat.com/providers/database/provider.go#LL43C16-L43C16

> @Victoremepunto then how the CI is passing? thinking

LOL - I added it myself when I added support for PostgreSQL 14 and forgot :facepalm:

**Pull request merged**
