### PR TITLE
cleanup(db): RHICOMPL-3251 drop account_number from accounts table

### PR DESCRIPTION
**Pull request by RoamingNoMaD**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by romanblanco — CHANGES_REQUESTED** [review]
one more here:

https://github.com/RoamingNoMaD/compliance-backend/blob/50e6e9c56414510fb55a9e569401e41ea6b6d527/db/seeds.dev.rb#L76

**Comment by vkrizan** [comment]
@RoamingNoMaD @romanblanco @skateman are we sure that we can remove account_numbers? See my forwarded email.

**Comment by romanblanco** [comment]
@vkrizan we can

**Review by romanblanco — APPROVED** [review]
LGTM :+1:

**Pull request merged**
