### PR TITLE
feat(RBAC): RHICOMPL-2710 Granular RBAC permissions

### PR DESCRIPTION
**Pull request by romanblanco**
Waiting for https://github.com/RedHatInsights/rbac-config/pull/249

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by marleystipich2 — APPROVED** [review]
Looks good to me! Thanks, @romanblanco!

**Comment by romanblanco** [comment]
Updated according to https://github.com/RedHatInsights/rbac-config/pull/254

**Comment by romanblanco** [comment]
Updated according to https://github.com/RedHatInsights/rbac-config/pull/254

**Comment by romanblanco** [comment]
PRs wes opened before the PSI outage (and subsequent migration to AWS) happened reopening in https://github.com/RedHatInsights/compliance-backend/pull/1249

**Pull request closed without merging**
