### PR TITLE
test(cgroup-limits): RHICOMPL-2905 add test coverage for cgroup-limits

### PR DESCRIPTION
**Pull request by Victoremepunto**
- Add E2E tests for cgroup-limits script
 - Bugfix for cgroup-limit script

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [X] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
06c3c664-7c9d-4bd6-8518-d475bdd9b51a
80e43330-0191-4a6b-8e70-303b95010ebd

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
51373b4e-c1d7-483b-9fc2-5010060929c1
d5fd40f3-9dcc-48bb-bd82-0fad51c75b68

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
128bb179-9e5f-49b8-82ab-c079b463fdfb
5f7bb884-4289-4626-9e82-991b1e4d6b5d

**Comment by romanblanco** [comment]
https://github.com/RedHatInsights/compliance-backend/pull/1277, removing cgroup-limits has just been merged.

@Victoremepunto, can this be closed?

**Comment by Victoremepunto** [comment]
We're removing the script so this won't be needed

**Pull request closed without merging**
