### PR TITLE
fix(Notification): RHICOMPL-2563 double serialize payload and context

### PR DESCRIPTION
**Pull request by skateman**
Apparently this is necessary :see_no_evil: 

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by romanblanco — APPROVED** [review]
Looks good :+1:

**Comment by marleystipich2** [comment]
@skateman Looks like your pr check is failing for the same reason that mine is 😢 I re-tested 2 or 3 times today and it keeps failing..

**Pull request merged**
