### PR TITLE
[stable] Align stable to master to test Cyndi integration

### PR DESCRIPTION
**Pull request by akofink**
No need to actually merge this. It's just here to test that the Cyndi changes get deployed properly to the smoke environment.

CC @Victoremepunto

### CODE REVIEW

**Comment by akofink** [comment]
@Victoremepunto I tried replaying the smoke tests again last night. It doesn't seem to have worked. Is that expected, or do I need to do something else to get a fresh build?

**Comment by Victoremepunto** [comment]
> @Victoremepunto I tried replaying the smoke tests again last night. It doesn't seem to have worked. Is that expected, or do I need to do something else to get a fresh build?

I can't find a response to why prometheus-exporter failed with 
```
error: update acceptor rejected compliance-prometheus-exporter-1: pods for rc 'ephemeral-01/compliance-prometheus-exporter-1' took longer than 600 seconds to become available
```

Rerunning the pipeline

**Comment by Victoremepunto** [comment]
> > @Victoremepunto I tried replaying the smoke tests again last night. It doesn't seem to have worked. Is that expected, or do I need to do something else to get a fresh build?
> 
> I can't find a response to why prometheus-exporter failed with
> 
> ```
> error: update acceptor rejected compliance-prometheus-exporter-1: pods for rc 'ephemeral-01/compliance-prometheus-exporter-1' took longer than 600 seconds to become available
> ```
> 
> Rerunning the pipeline

This is now blocked by https://github.com/RedHatInsights/e2e-deploy/pull/2698

**Comment by akofink** [comment]
@Victoremepunto replayed the smoke tests again :crossed_fingers:

**Comment by akofink** [comment]
Closing. I'll submit a new stable PR with the cert-auth work included.

**Pull request closed without merging**
