### PR TITLE
revert(stage): RHICOMPL-2955 revert stage by 2 commits

### PR DESCRIPTION
**Pull request by skateman**
Reverting commits:
e47d95017fd09fefbdcacdb6cbdac988c72c37ed
cd964c5c31cf16aef12296e85c3119fc45416891

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
7993a412-8005-479f-9bde-197cb620969d
a1bc578f-effb-4336-a201-a8b6f3365ab6

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
133fc594-4abe-4c9c-afae-5e0a5577a281
5f45361c-cb12-4661-b980-7ead8baf7881

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
6d9b8c14-e7b1-46ae-bc65-d05f5bde63c2
fe6340f8-3d38-4a9a-8581-d0db1a8e9ca3

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
985d4f33-761d-4538-afe1-19746a04deb8
e653496f-2d0b-4200-9840-656ea43130ad

**Comment by skateman** [comment]
No longer necessary...

**Pull request closed without merging**
