### PR TITLE
cleanup(RBAC): Remove workaround of setting header

### PR DESCRIPTION
**Pull request by romanblanco**
https://github.com/RedHatInsights/insights-rbac-api-client-ruby/pull/11

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by skateman** [comment]
Probably it's not enough, you'd also need to push out the new version (to rubygems) and bump it in the gemfile(.lock)

**Comment by romanblanco** [comment]
True, waiting for https://github.com/RedHatInsights/insights-rbac-api-client-ruby/pull/13

**Comment by romanblanco** [comment]
https://rubygems.org/gems/insights-rbac-api-client/versions/1.0.1 is out now

**Comment by skateman** [comment]
you'd probably need to update the lockfile to make it green

**Review by skateman — APPROVED** [review]

**Pull request merged**
