### PR TITLE
chore(ci): add security-scan script to enable jenkins security scan job

### PR DESCRIPTION
**Pull request by casey-williams-rh**
## Overview

Adding the Jenkins Security Scanning Workflow, and removing the GH Security Workflow file. This script will provide the same level of support as the standard PlatSec GitHub Workflow, but will run on a RHEL-Based Jenkins Node.

A copy of the [security-scan-source-template.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan-source-template.sh) has been added to this repo, and the (GitHub) `platsec-gh-vulnerability-scan` Jenkins Job has be added to the Compliance-Backend `build.yml` in App-Interface.

Similar to the standard GitHub Workflow, we can accommodate feature requests and provide updates on the fly and with full transparency. The `security-scan-source-template.sh` script, which sources the main [security-scan.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan.sh) script, allows us to support multiple teams without having to open up multiple PRs across multiple repos.

In the checks associated with this PR you will find the `ci.int.devshift.net Grype Vulnerability Scan`. Inside of Jenkins you will see the output of the scan. The scan consists of the following items:

- `Software Bill of Materials (SBOM)` | Text (Human Readable) & JSON (Verbose)
- `Vulnerability Scan (Full Listing)` |  | Text (Human Readable) & JSON (Verbose)
- `Vulnerability Scan (Fixable)` |  | Text (Human Readable) & JSON (Verbose)

The Jenkins job will fail if there is a fixable vulnerability is found with a severity of `High` or greater. 

For more information please check out the [PlatSec GH Workflow repo](https://github.com/RedHatInsights/platform-security-gh-workflow).

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by skateman** [comment]
@Victoremepunto isn't this something that could be somehow defined in the Jenkinsfile so we don't need an extra bash script?

**Comment by Victoremepunto** [comment]
@skateman  this is related to how the pipeline is configured. 

Your "PR check" Job is defined on a Jenkinsfile, but again that's for PR jobs. 

This is a different Job, a security scan job, defined as the old "bash script based" Jobs, search for "platsec" and "vulnerability-scan" in app-interface (can't link it here).

if you're asking "Couldn't this be implemented as a Jenkinsfile"  the answer is "yes" but it seems @casey-williams-rh  is implementing this job across the board using the old templates (the Bash script based ones).

It depends when does this has to run, if it's going to run on every PR, you could add a separate branch and run it as a step as part of your Jenkinsfile.

I'd say - I'd see this as a "how many jobs I need to keep" as opposed to "can I do all of it in the same Jenkinsfile". Each new job requ

You can redefine the script's path though, so you can hide it "somewhere else" and set the new path in app-interface (I don't think @casey-williams-rh  would find an issue with that)

LMK if that works for you.

**Comment by skateman** [comment]
Ideally, we should be getting rid of bash scripts and not introduce new ones 😞

**Comment by casey-williams-rh** [comment]
@skateman , This script has been developed with the goal of delivering scanning to teams as quickly as possible. It is important to note, however, that this particular solution is not permanent. We are currently working on integrating scanning functionality directly into Konflux. So, this script represents a transitional measure until we complete the migration to Konflux.

CC: @Victoremepunto

**Pull request merged**
