### PR TITLE
chore(clowder): Bump up CPU to 800m max for sidekiq/ssg pods

### PR DESCRIPTION
**Pull request by akofink**
This affects sidekiq and import-ssg.

Signed-off-by: Andrew Kofink <akofink@redhat.com>

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by Victoremepunto — CHANGES_REQUESTED** [review]
please increase the CPU request up to 400m

**Comment by Victoremepunto** [comment]
> please increase the CPU request up to 400m

So there's not such a big difference between request / limit

**Comment by akofink** [comment]
> please increase the CPU request up to 400m

Why? The limit is supposed to be 10 times the request. For memory, limit should be 2 times the request.

**Comment by Victoremepunto** [comment]
> > please increase the CPU request up to 400m
> 
> Why? The limit is supposed to be 10 times the request. For memory, limit should be 2 times the request.

No, I think there might be  a misunderstanding here :) - the maximum ratio is 10 , that doesn't mean it has to be 10... 

I'm thinking of this situation: the controller needs to bring up your pod, and since it just requires 80m cpu, it allocates it on a node that has 200m free. so it "fits". then if it needs to bump the CPU allocation,  it will have to evict the pod and spawn it on a different node. 

The bigger the distance between both request and limit is, the higher is the risk to fall into this situation. it's all going to be handled by Openshift, but there's no need to request under 100m if we're likely going to need CPU several orders of magnitude greater than what we just requested.

**Review by Victoremepunto — APPROVED** [review]
let's just leave it as it is

**Pull request merged**
