### PR TITLE
fix(import): RHICOMPL-2833 - Update ProfileRuleGroups import

### PR DESCRIPTION
**Pull request by marleystipich2**
This is going to fail until the [openscap parser changes](https://github.com/OpenSCAP/openscap_parser/pull/37) are merged and deployed and then we can update the gem version in our Gemfile.

I tested locally with the `openscap_parser` gem pointing to the commit in the PR and everything worked correctly.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by romanblanco — APPROVED** [review]
LGTM :+1:

**Comment by romanblanco** [comment]
Code looks good. @marleystipich2 Did you verify with OpenSCAP team that the namespace is a constant? /cc @skateman

**Comment by marleystipich2** [comment]
@romanblanco Thanks for reviewing! I didn't check with them that the namespace is constant because the way that we have `selected_group_ids` and `selected_rule_ids` is set up now, in the openscap parser, will work with any namespace. So if the namespace changes in the future, these methods will still work correctly. If you want to take a look at this a little more, here's the [openscap parser PR](https://github.com/OpenSCAP/openscap_parser/pull/37/files) with these updates!

**Pull request merged**
