### PR TITLE
feat(RBAC): RHICOMPL-2710 allow read remediation permission for all roles

### PR DESCRIPTION
**Pull request by romanblanco**
To be up-to-date with Stage & Prod environment:
https://github.com/RedHatInsights/rbac-config/pull/285
https://github.com/RedHatInsights/rbac-config/pull/264

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by skateman** [comment]
This is development-only, right?

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
7e254dc3-b33e-4847-b0b6-1db11f8267c6
b99b7ac8-b248-4071-8728-6b30eb89e89f

**Comment by romanblanco** [comment]
May be closed: https://docs.google.com/spreadsheets/d/13UTUUWwpJTvjBlhY3nbmv5I5Z-JtNkFyMQ4HLt9taYY/edit?disco=AAAAaOYYbo8

**Comment by romanblanco** [comment]
> This is development-only, right?

@skateman Yes

**Review by skateman — APPROVED** [review]
The Seal of Approval

**Pull request merged**
