### PR TITLE
fix(RuleGroups): RHICOMPL-2956 update ancestry for rule groups correctly

### PR DESCRIPTION
**Pull request by marleystipich2**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
5a17c420-0270-417c-b0c2-63fc73d3a9cc
c7b86ff8-f2c8-4e5b-8fb4-36a3b3112e19

**Comment by skateman** [comment]
How would this work with already stored rule groups? Is a forced import sufficient? If yes, please clear the revisions in a migration.

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
1b0b0534-81ca-4c2b-a12f-f1df6176efbb
ea353a92-f778-4ec1-975f-f3cbefd208ac

**Review by skateman — APPROVED** [review]
The Seal of Approval
Let's hold off the merging before the RBAC fix

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
5fa44245-4053-4bda-adb0-a0150bdc04c6
f2f0273e-f54f-47fd-b588-e44e830f408f

**Pull request merged**
