### PR TITLE
fix(Account): RHICOMPL-1558 Add index on account_number

### PR DESCRIPTION
**Pull request by akofink**
This is just a normal index for now. We will need to go back and update
it to be a unique index and clean up duplicate accounts. This is an
endeavor to speed up our pundit policies, especially when querying
hosts.

Signed-off-by: Andrew Kofink <akofink@redhat.com>

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [X] Input Validation
- [X] Output Encoding
- [X] Authentication and Password Management
- [X] Session Management
- [X] Access Control
- [X] Cryptographic Practices
- [X] Error Handling and Logging
- [X] Data Protection
- [X] Communication Security
- [X] System Configuration
- [X] Database Security
- [X] File Management
- [X] Memory Management
- [X] General Coding Practices

### CODE REVIEW

**Comment by skateman** [comment]
Can you also set up a `belongs_to` on the `Host` (and any other related field)?

**Review by vkrizan — APPROVED** [review]
LGTM.

@akofink do you have any measurements how much this speeded up querying hosts?

**Comment by akofink** [comment]
Unfortunately, the way we have the local devel DB view set up using dblink causes a severe bottleneck, so I can't properly test what kind of speedup we'll see with this change for hosts specifically; however, all our pundit policies for all resources look up an account by account number [here](https://github.com/RedHatInsights/compliance-backend/blob/master/app/controllers/concerns/authentication.rb#L98). I probably don't need to `explain` it to you ;) (11k accounts below):

```rb
[39] pry(main)> Account.where(account_number: '1212729').explain # with index
  Account Load (0.2ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."account_number" = $1  [["account_number", "1212729"]]
=> EXPLAIN for: SELECT "accounts".* FROM "accounts" WHERE "accounts"."account_number" = $1 [["account_number", "1212729"]]
                                            QUERY PLAN
--------------------------------------------------------------------------------------------------
 Index Scan using index_accounts_on_account_number on accounts  (cost=0.29..8.30 rows=1 width=39)
   Index Cond: ((account_number)::text = '1212729'::text)
(2 rows)

[40] pry(main)> Account.where(account_number: '1212729').explain # without index
  Account Load (1.6ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."account_number" = $1  [["account_number", "1212729"]]
=> EXPLAIN for: SELECT "accounts".* FROM "accounts" WHERE "accounts"."account_number" = $1 [["account_number", "1212729"]]
                        QUERY PLAN
-----------------------------------------------------------
 Seq Scan on accounts  (cost=0.00..228.66 rows=1 width=39)
   Filter: ((account_number)::text = '1212729'::text)
(2 rows)
```

**Comment by akofink** [comment]
> Can you also set up a belongs_to on the Host (and any other related field)?

Check the account.rb model. Host `belongs_to :account`; Account `has_many :hosts`. Am I missing a relation?

**Comment by skateman** [comment]
My bad, missed those :see_no_evil: got confused because of the `account` vs `account_number` when dealing with host factories.

**Pull request merged**
