### PR TITLE
fix(openapi): RHICOMPL-2075 fix swagger/openapi for tagging

### PR DESCRIPTION
**Pull request by skateman**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by skateman** [comment]
@akofink when I run swaggerize, the generated JSON doesn't contain any examples, so I'm not sure how to deal with this :confused:

**Review by vkrizan — APPROVED** [review]

**Comment by akofink** [comment]
@skateman ever since the FactoryBot swap in our tests, this is painful. We still need to go back and create records from the factories for our specs which demonstrate how the API responses can look. For now, you'll have to generate the openapi.json and then I suggest using `git add -i` to add the examples hunk by hunk to the openapi.json (it should only be the one for systems).

**Comment by skateman** [comment]
> For now, you'll have to generate the openapi.json and then I suggest using `git add -i` to add the examples hunk by hunk to the openapi.json (it should only be the one for systems).

@akofink the problem is that it doesn't generate anything else than what is in this PR and I suspect that's not enough, i.e due to the missing records we have no example related to the tags :shrug:

**Comment by akofink** [comment]
> due to the missing records we have no example related to the tags

Ah! That makes sense :laughing: Can we modify a host to give it tags for the test, then? Seems like maybe we need to enhance the hosts factory.

**Comment by skateman** [comment]
> > due to the missing records we have no example related to the tags
> 
> Ah! That makes sense  Can we modify a host to give it tags for the test, then? Seems like maybe we need to enhance the hosts factory or just add tags manually to the existing host: https://github.com/RedHatInsights/compliance-backend/blob/master/spec/integration/systems_spec.rb#L8

Yeah, this won't work either, at least not with `bin/rake rswag:specs:swaggerize` :confused: even if I have everything set up correctly in the `before` hook. It's suspicious that the hook doesn't even get called :disappointed: at least I can't access my custom breakpoint that I added there.

**Comment by akofink** [comment]
The only way I've ever been able to regenerate the openapi.json is by modifying the command run with that rake task:

```
ruby -I/usr/local/bundle/gems/rspec-core-3.9.2/lib:/usr/local/bundle/gems/rspec-support-3.9.3/lib /usr/local/bundle/gems/rspec-core-3.9.2/exe/rspec --pattern spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --order defined
```

Last I checked, the rake task was adding --dry-run. It's been a very long time since I looked into this or if it works today.

**Comment by skateman** [comment]
@akofink we should document this somewhere, or create a rake task :shrug: because I didn't even know about it

**Review by akofink — APPROVED** [review]
Thanks, @skateman! Sorry about the rswag nonsense :disappointed:

**Pull request merged**
