### PR TITLE
[stable][RHICOMPL-1040][RHICOMPL-1042]

### PR DESCRIPTION
**Pull request by akofink**
https://github.com/RedHatInsights/compliance-backend/pull/605 + some more minor bug fixes

:no_smoking:

### CODE REVIEW

**Review by vkrizan — CHANGES_REQUESTED** [review]
Can you please add changes from PR #609, once merged?

**Review by vkrizan — APPROVED** [review]

**Comment by vkrizan** [comment]
@akofink Please hold with the uniqueness commits. I'm not confident that they are correct.

**Comment by vkrizan** [comment]
Fix incoming via #617

**Review by vkrizan — APPROVED** [review]

**Comment by akofink** [comment]
Updated with latest changes from the work on COMP-E-129. :no_smoking: :crossed_fingers:

**Pull request merged**
