### PR TITLE
Remove dead code in Xccdf report parser

### PR DESCRIPTION
**Pull request by vkrizan**

### CODE REVIEW

**Comment by vkrizan** [comment]
I guess the whole `Xccdf::Profiles` could go away.

**Review by akofink — APPROVED** [review]
Thanks. Why is it draft? I think we should keep these concerns, otherwise we'll have to put them all together in (i.e.) Xccdf::Util or something, and rubocop will start complaining about class length, etc.

**Comment by vkrizan** [comment]
@akofink I've changed it to draft, as the whole concern can go away. But I haven't verified it yet.

**Comment by akofink** [comment]
If you remove the concern, `save_profiles` still has to go somewhere. I'd like to keep the concern since it matches the pattern used by the rest of the parsing code.

**Comment by vkrizan** [comment]
@akofink Yes. I've missed the aliased name being used.

**Review by akofink — APPROVED** [review]
Thanks, @vkrizan!

**Pull request merged**
