### PR TITLE
chore(cleanup): remove unused floorist props

### PR DESCRIPTION
**Pull request by vkrizan**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by Victoremepunto — APPROVED** [review]
This should've gone out along with  13b5184ebe27188d05709c3897e5002a407f26bb 

LGTM

**Review by Victoremepunto — CHANGES_REQUESTED** [review]
Actually, you need to remove the same props from `clowdapp-minimal.yaml`

**Comment by vkrizan** [comment]
Yep, and yep.

**Review by skateman — APPROVED** [review]
The Seal of Approval

**Review by Victoremepunto — APPROVED** [review]
Thanks

**Pull request merged**
