### PR TITLE
ci(labeller): RHICOMPL-3202 label PRs that update GraphQL files

### PR DESCRIPTION
**Pull request by Victoremepunto**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by skateman** [comment]
labeler or labeller, please make it consistent :pray:

**Comment by vkrizan** [comment]
`app/graphql/remove_this.rb` do not forget to remove it  :wink:

**Comment by Victoremepunto** [comment]
> labeler or labeller, please make it consistent pray

it was a typo, fixed already

**Comment by Victoremepunto** [comment]
@skateman , @vkrizan  sorry, I openened a new one as a follow-up: #1398

**Pull request closed without merging**
