### PR TITLE
devel(CI): RHICOMPL-2542 set up github actions on master

### PR DESCRIPTION
**Pull request by skateman**
Sets up some basic CI stuff in order to be able to upload coverage results to codecov.

### CODE REVIEW

**Review by marleystipich2 — APPROVED** [review]
Looks good to me! Thanks, @skateman!

**Comment by sthirugn** [comment]
thank you David. I am wondering we are running the tests on ubuntu-latest? are there no centos options to pick from?

**Comment by skateman** [comment]
> thank you David. I am wondering we are running the tests on ubuntu-latest? are there no centos options to pick from?

https://github.com/actions/virtual-environments#available-environments

**Comment by sthirugn** [comment]
ok thank you David

**Pull request merged**
