### PR TITLE
feat(clowder): RHICOMPL-2736 extract import-ssg schedule to a param

### PR DESCRIPTION
**Pull request by skateman**
Needs to be retested after app-interface changes are in to verify that it's faster 

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x ] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by vkrizan — APPROVED** [review]
LGTM

**Review by Victoremepunto — APPROVED** [review]
Looks good, thanks !

**Pull request merged**
