### PR TITLE
fix(rbac): RHICOMPL-2955 pass the original identity header

### PR DESCRIPTION
**Pull request by skateman**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
6f918709-953b-4f43-a8ca-d2fcf73e7e91
dbb8ddcb-20ab-477d-b1e3-d641fb8da295

**Review by vkrizan — APPROVED** [review]
Make sense!

Can the `User#authorized_to?` be removed after this?

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
7e15a47a-bbaf-4537-8313-c3afa7359269
fbf11afc-874e-4a92-9dd3-bf4318153d6a

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
0665ade2-bdb2-4b6c-9f2d-d4bb2097506a
c17fb993-76b4-489a-80e2-bde6c51cc5c6

**Pull request merged**
