### PR TITLE
feat(db): RHICOMPL-2970 define the job for org_id translation

### PR DESCRIPTION
**Pull request by skateman**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
6a01de40-e794-457c-9fda-92893aa09a1f
f124d918-3c3e-4bc7-9a82-83bdbb133638

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
0a9b0b97-40ee-4c80-bfdb-d5b05680b288
2c7af0bf-26a7-4809-ae1c-18cca0ebd5c0

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3634e5e1-57e1-409d-9242-91e390a00396
d3991cd6-ae06-4ca8-a329-9e4b66500f4d

**Review by romanblanco — APPROVED** [review]
LGTM :+1:

**Pull request merged**
