### PR TITLE
chore(deps): update rails to 8.0.0

### PR DESCRIPTION
**Pull request by skateman**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by skateman** [comment]
Blocked by https://github.com/yosiat/panko_serializer/issues/166

**Comment by vkrizan** [comment]
This is great news!

@skateman panko just released a fixed version.

Are there any other breaking changes?

**Comment by skateman** [comment]
LOL yes, Rails 8 support 😆

**Review by RoamingNoMaD — APPROVED** [review]
lgtm, ty David <3

**Pull request merged**
