### PR TITLE
patch(RHICOMPL-2815): Remove custom deployment timeout value

### PR DESCRIPTION
**Pull request by Victoremepunto**
After https://github.com/RedHatInsights/bonfire/commit/a5786c0d9337a8b95541e91825b77b6a1ad29d58 seems we don't need a custom timeout value anymore.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by vkrizan — APPROVED** [review]
LGTM. Thanks!

Instead of the `patch` it might be `refactor:` or `ci:`.
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by Victoremepunto** [comment]
> LGTM. Thanks!
> 
> Instead of the `patch` it might be `refactor:` or `ci:`. https://www.conventionalcommits.org/en/v1.0.0/

Thank you, I was not aware of the specific keywords, I thought they were "free to choose" - this makes me wonder - would it be interesting to configure a linter to enforce our commit syntax ?

**Comment by Victoremepunto** [comment]
> > LGTM. Thanks!
> > Instead of the `patch` it might be `refactor:` or `ci:`. https://www.conventionalcommits.org/en/v1.0.0/
> 
> Thank you, I was not aware of the specific keywords, I thought they were "free to choose" - this makes me wonder - would it be interesting to configure a linter to enforce our commit syntax ?

@vkrizan  Actually, I went ahead and created https://github.com/RedHatInsights/compliance-backend/pull/1240 , hope you like it, goes without saying a review is welcome :)

**Comment by vkrizan** [comment]
Thanks @Victoremepunto. I usually prefer documentation over strict linting rules. :slightly_smiling_face:

**Pull request merged**
