### PR TITLE
fix(RHICOMPL-2851): nullify remediation_issue_id if no remediation

### PR DESCRIPTION
**Pull request by skateman**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by vkrizan** [comment]
@skateman unit test? :grin:

**Comment by skateman** [comment]
> @skateman unit test? grin

@vkrizan if Jenkins is on PTO, I can be a bit slower with unit tests :wink:

**Comment by Victoremepunto** [comment]
@skateman  I'm wondering if we should leave the former field intact and simply expose the `remediation_available` rule attribute. That way we would avoid change the API spec (making the remediation_issue_id nullable).

**Comment by skateman** [comment]
I don't want to adjust the API if we can avoid it.

**Comment by skateman** [comment]
> @skateman This looks good to me but I see Victor's comment above and I'm kind of confused what the purpose of adding `nullable: true ` on the `remediation_issue_id` is? Was this necessary?

Some rules have no remediation available, their issue ID should be `nil`

**Pull request merged**
