### PR TITLE
cleanup(GraphQL): RHICOMPL-2895 replace the majorOsVersion

### PR DESCRIPTION
**Pull request by skateman**
We don't need both, the `majorOsVersion` is being cleaned up in the frontend soon.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3d297bc1-1c67-4618-a21e-0fa5a47ca146
447a66a4-5520-4cd8-acce-ae81972d71c4

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
6535ebaf-598a-4e7e-a5a7-76b9e3addcec
72afbeb1-85b5-4199-aafe-63a5a166ba60

**Review by romanblanco — APPROVED** [review]
LGTM :+1:

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
4d61c939-a139-4102-b74e-5007f8910b85
d3611539-7728-4712-ba4c-bbbe4930333f

**Pull request merged**
