### PR TITLE
feat(Benchmark): RHICOMPL-3402 get rules and groups for Benchmark

### PR DESCRIPTION
**Pull request by marleystipich2**
This PR currently conflicts with https://github.com/RedHatInsights/compliance-backend/pull/1273 so depending on which one is merged first, we'll need to resolve the conflicts at some point. 

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by skateman — CHANGES_REQUESTED** [review]
I like it :heart_eyes: but could you please separate this into 2 commits?
refactor(Profile): RHICOMPL-xxxx extract retrieving of hierarchical rules and groups
feat(Benchmark): RHICOMPL-xxxx hierarchical rules and groups for Benchmarks

**Comment by skateman** [comment]
Also please try to fit into the commit message length:
image

**Comment by marleystipich2** [comment]
> Test failure seems relevant...

Hmm.. the test is passing locally. Looking into this 🤔

**Comment by marleystipich2** [comment]
The tests should be good now 👍

**Review by skateman — APPROVED** [review]
The Seal of Approval

**Pull request merged**
